=== BackupTheBerlios/ch0p-svn/simple-grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Tom Gelhausen (IPD, Uni-Karlsruhe) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="grammar">
		<xs:annotation>
			<xs:documentation>This element specifies a grammar.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:choice>
					<xs:element name="rule">
						<xs:annotation>
							<xs:documentation>This element specifies one rule.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:all>
								<xs:element name="lhs" type="sequenceType">
									<xs:annotation>
										<xs:documentation>This element specifies the left hand side of the rule.</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="rhs" type="sequenceType">
									<xs:annotation>
										<xs:documentation>This element specifies the right hand side of the rule</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:all>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="startsymbol" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="sequenceType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="term">
					<xs:complexType>
						<xs:attribute name="value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="nonterm">
					<xs:complexType>
						<xs:attribute name="value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== BackupTheBerlios/ch0p-svn/g4.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simple-grammar.xsd" startsymbol="S0">
	<rule>
		<lhs><nonterm value="S0"/></lhs>
		<rhs><nonterm value="S1"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="S1"/></lhs>
		<rhs><nonterm value="A"/><nonterm value="A"/><nonterm value="A"/><nonterm value="A"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><term value="a"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><nonterm value="E"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="E"/></lhs>
		<rhs></rhs>
	</rule>
</grammar>

=== BackupTheBerlios/ch0p-svn/g2.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simple-grammar.xsd" startsymbol="S0">
	<rule>
		<lhs><nonterm value="S0"/></lhs>
		<rhs><nonterm value="S1"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="S1"/></lhs>
		<rhs><nonterm value="A"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="S1"/></lhs>
		<rhs><term value="a"/><nonterm value="S1"/><term value="b"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><term value="a"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><nonterm value="A"/><term value="a"/></rhs>
	</rule>
</grammar>

=== BackupTheBerlios/ch0p-svn/g3.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simple-grammar.xsd" startsymbol="S0">
	<rule>
		<lhs><nonterm value="S0"/></lhs>
		<rhs><nonterm value="S1"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="S1"/></lhs>
		<rhs><term value="a"/><nonterm value="A"/><term value="b"/><nonterm value="B"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><term value="a"/><nonterm value="A"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="A"/></lhs>
		<rhs><term value="a"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="B"/></lhs>
		<rhs><term value="b"/><nonterm value="B"/></rhs>
	</rule>
	<rule>
		<lhs><nonterm value="B"/></lhs>
		<rhs><term value="b"/></rhs>
	</rule>
</grammar>
